# Generated by Django 6.0.3 on 2026-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to='listing_images/'),
        ),
    ]
